# Node-specific SNMP config for frr-leaf-4
sysLocation    PDSNO ContainerLab
sysContact     pdsno-lab@tenkei.dev
sysName        frr-leaf-4

rocommunity public default
agentAddress udp:161

view   systemonly  included   .1.3.6.1.2.1.1
view   systemonly  included   .1.3.6.1.2.1.2
view   systemonly  included   .1.3.6.1.2.1.25.1
